// frontend/src/sections/Hero.tsx
// Hero section component
import { motion } from 'framer-motion';
import { ArrowDown, Sparkles, ChefHat } from 'lucide-react';
import { Button } from '@/components/ui/button';

const floatingIngredients = [
  { icon: '🍅', delay: 0, x: '8%', y: '15%', duration: 5 },
  { icon: '🥬', delay: 0.5, x: '88%', y: '12%', duration: 6 },
  { icon: '🥕', delay: 1, x: '82%', y: '65%', duration: 4.5 },
  { icon: '🧄', delay: 0.3, x: '12%', y: '60%', duration: 7 },
  { icon: '🥚', delay: 0.8, x: '48%', y: '8%', duration: 5.5 },
  { icon: '🧅', delay: 1.2, x: '92%', y: '45%', duration: 6.5 },
  { icon: '🥦', delay: 0.6, x: '5%', y: '38%', duration: 5 },
  { icon: '🍋', delay: 1.5, x: '58%', y: '72%', duration: 6 },
];

export function Hero() {
  const scrollToIngredients = () => {
    document.getElementById('ingredients')?.scrollIntoView({ behavior: 'smooth' });
  };

  return (
    <section
      className="relative min-h-screen flex items-center justify-center overflow-hidden bg-gradient-to-br from-[var(--warm-cream)] via-[#FFF5E0] to-[var(--warm-beige)]"
    >
      {/* Decorative Background Elements */}
      <div className="absolute inset-0 overflow-hidden">
        {/* Subtle pattern */}
        <svg className="absolute w-full h-full opacity-[0.03]" viewBox="0 0 100 100" preserveAspectRatio="none">
          <pattern id="dots" width="8" height="8" patternUnits="userSpaceOnUse">
            <circle cx="2" cy="2" r="1" fill="#E8913A" />
          </pattern>
          <rect width="100" height="100" fill="url(#dots)" />
        </svg>
        
        {/* Warm gradient orbs */}
        <motion.div
          className="absolute w-[500px] h-[500px] rounded-full bg-[var(--warm-orange)]/8 blur-3xl"
          style={{ top: '-5%', left: '-10%' }}
          animate={{
            scale: [1, 1.15, 1],
            opacity: [0.4, 0.6, 0.4],
          }}
          transition={{ duration: 8, repeat: Infinity, ease: 'easeInOut' }}
        />
        <motion.div
          className="absolute w-[400px] h-[400px] rounded-full bg-[var(--fresh-green)]/8 blur-3xl"
          style={{ bottom: '-5%', right: '-5%' }}
          animate={{
            scale: [1.1, 1, 1.1],
            opacity: [0.3, 0.5, 0.3],
          }}
          transition={{ duration: 10, repeat: Infinity, ease: 'easeInOut' }}
        />
      </div>

      {/* Floating Ingredients */}
      {floatingIngredients.map((item, index) => (
        <motion.div
          key={index}
          className="absolute text-4xl md:text-5xl select-none pointer-events-none"
          style={{
            left: item.x,
            top: item.y,
          }}
          initial={{ opacity: 0, scale: 0 }}
          animate={{
            opacity: 1,
            scale: 1,
            y: [0, -15, 0],
            rotate: [0, 3, -3, 0],
          }}
          transition={{
            opacity: { delay: item.delay + 0.3, duration: 0.5 },
            scale: { delay: item.delay + 0.3, duration: 0.5, type: 'spring' },
            y: { delay: item.delay, duration: item.duration, repeat: Infinity, ease: 'easeInOut' },
            rotate: { delay: item.delay, duration: item.duration * 1.3, repeat: Infinity, ease: 'easeInOut' },
          }}
        >
          {item.icon}
        </motion.div>
      ))}

      {/* Main Content */}
      <div className="relative z-10 max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 text-center">
        {/* Logo Display */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6, delay: 0.1 }}
          className="mb-8"
        >
          <div className="relative inline-block">
            <motion.div
              className="w-28 h-28 md:w-36 md:h-36 mx-auto rounded-3xl overflow-hidden shadow-warm-lg"
              whileHover={{ scale: 1.05, rotate: 2 }}
              transition={{ type: 'spring', stiffness: 300 }}
            >
              <img 
                src="/logo.jpg" 
                alt="下厨有谱" 
                className="w-full h-full object-cover"
              />
            </motion.div>
            {/* Steam animation */}
            <motion.div
              className="absolute -top-4 left-1/2 -translate-x-1/2"
              animate={{ opacity: [0, 0.6, 0], y: [0, -20] }}
              transition={{ duration: 2.5, repeat: Infinity, ease: 'easeOut' }}
            >
              <span className="text-2xl">💨</span>
            </motion.div>
          </div>
        </motion.div>

        {/* Brand Name */}
        <motion.h1
          initial={{ opacity: 0, y: 30 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.8, delay: 0.2, ease: [0.16, 1, 0.3, 1] }}
          className="text-5xl sm:text-6xl md:text-7xl font-serif font-bold text-[var(--text-brown)] mb-4 tracking-tight"
        >
          下厨有谱
        </motion.h1>

        {/* Slogan */}
        <motion.p
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6, delay: 0.4 }}
          className="text-xl md:text-2xl text-[var(--text-brown-light)] mb-6 font-light"
        >
          承包你的一日三餐与四季风味
        </motion.p>

        {/* Description */}
        <motion.p
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6, delay: 0.5 }}
          className="text-base md:text-lg text-[var(--text-brown-light)]/80 max-w-xl mx-auto mb-10 leading-relaxed"
        >
          输入冰箱里的食材，AI智能推荐最适合的菜谱
          <br className="hidden sm:block" />
          让每一餐都充满家的味道
        </motion.p>

        {/* CTA Buttons */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6, delay: 0.7 }}
          className="flex flex-col sm:flex-row gap-4 justify-center items-center"
        >
          <Button
            size="lg"
            onClick={scrollToIngredients}
            className="bg-[var(--warm-orange)] hover:bg-[var(--warm-orange-dark)] text-white rounded-full px-8 py-6 text-base font-medium shadow-warm hover:shadow-warm-lg transition-all group"
          >
            <ChefHat className="w-5 h-5 mr-2" />
            开始烹饪
            <motion.span
              className="ml-2 inline-block"
              animate={{ y: [0, 3, 0] }}
              transition={{ duration: 1.5, repeat: Infinity }}
            >
              <ArrowDown className="w-4 h-4" />
            </motion.span>
          </Button>
          <Button
            size="lg"
            variant="outline"
            className="border-2 border-[var(--fresh-green)]/30 text-[var(--fresh-green)] hover:bg-[var(--fresh-green)]/5 rounded-full px-8 py-6 text-base font-medium"
          >
            <Sparkles className="w-5 h-5 mr-2" />
            浏览热门菜谱
          </Button>
        </motion.div>

        {/* Stats */}
        <motion.div
          initial={{ opacity: 0, y: 30 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.8, delay: 0.9 }}
          className="mt-16 grid grid-cols-3 gap-6 max-w-md mx-auto"
        >
          {[
            { value: '1000+', label: '精选菜谱', color: 'text-[var(--warm-orange)]' },
            { value: '50+', label: '食材种类', color: 'text-[var(--fresh-green)]' },
            { value: '10万+', label: '快乐家庭', color: 'text-[var(--tomato-red)]' },
          ].map((stat, index) => (
            <motion.div
              key={index}
              className="text-center"
              initial={{ opacity: 0, scale: 0.8 }}
              animate={{ opacity: 1, scale: 1 }}
              transition={{ delay: 1 + index * 0.1, type: 'spring' }}
            >
              <div className={`text-2xl md:text-3xl font-serif font-bold ${stat.color}`}>{stat.value}</div>
              <div className="text-sm text-[var(--text-brown-light)]/70 mt-1">{stat.label}</div>
            </motion.div>
          ))}
        </motion.div>
      </div>

      {/* Bottom Gradient Fade */}
      <div className="absolute bottom-0 left-0 right-0 h-24 bg-gradient-to-t from-[var(--warm-cream)] to-transparent" />
    </section>
  );
}

// astro/src/components/sections/Hero.vue
<script setup lang="ts">
import { ref } from 'vue';
import Button from '../ui/Button.vue';

const floatingIngredients = [
  { icon: '🍅', delay: 0, x: '10%', y: '20%', duration: 6 },
  { icon: '🥬', delay: 1, x: '85%', y: '15%', duration: 7 },
  { icon: '🥕', delay: 2, x: '75%', y: '70%', duration: 5 },
  { icon: '🧄', delay: 0.5, x: '15%', y: '65%', duration: 8 },
  { icon: '🥚', delay: 1.5, x: '50%', y: '10%', duration: 6.5 },
  { icon: '🧅', delay: 2.5, x: '90%', y: '50%', duration: 7.5 },
  { icon: '🥦', delay: 0.8, x: '5%', y: '40%', duration: 5.5 },
  { icon: '🍋', delay: 1.8, x: '60%', y: '75%', duration: 6.8 },
];

function scrollToIngredients() {
  const element = document.getElementById('ingredients');
  if (element) {
    element.scrollIntoView({ behavior: 'smooth' });
  }
}
</script>

<template>
  <section class="relative min-h-screen flex items-center justify-center overflow-hidden bg-gradient-to-br from-[#e9f0ec] via-white to-[#f6f6f6]">
    <!-- Animated Background Pattern -->
    <div class="absolute inset-0 overflow-hidden">
      <svg class="absolute w-full h-full opacity-5" viewBox="0 0 100 100" preserveAspectRatio="none">
        <pattern id="grid" width="10" height="10" patternUnits="userSpaceOnUse">
          <circle cx="1" cy="1" r="1" fill="#2e5c41" />
        </pattern>
        <rect width="100" height="100" fill="url(#grid)" />
      </svg>

      <!-- Gradient Orbs -->
      <div
        class="absolute w-[600px] h-[600px] rounded-full bg-[#2e5c41]/10 blur-3xl gradient-orb"
        style="top: '-10%', left: '-10%'"
      />
      <div
        class="absolute w-[500px] h-[500px] rounded-full bg-[#ff8a01]/10 blur-3xl gradient-orb"
        style="bottom: '-5%', right: '-5%'; animation-delay: 1s;"
      />
    </div>

    <!-- Floating Ingredients -->
    <div
      v-for="(item, index) in floatingIngredients"
      :key="index"
      class="absolute text-5xl md:text-6xl select-none pointer-events-none floating-ingredient"
      :style="{
        left: item.x,
        top: item.y,
        animationDelay: `${item.delay}s`,
        animationDuration: `${item.duration}s`
      }"
    >
      {{ item.icon }}
    </div>

    <!-- Main Content -->
    <div class="relative z-10 max-w-5xl mx-auto px-4 sm:px-6 lg:px-8 text-center">
      <!-- Badge -->
      <div class="inline-flex items-center gap-2 bg-white/80 backdrop-blur-sm rounded-full px-4 py-2 shadow-lg mb-8 animate-fade-in">
        <svg class="w-4 h-4 text-[#ff8a01]" fill="currentColor" viewBox="0 0 24 24">
          <path d="M12 2L15.09 8.26L22 9.27L17 14.14L18.18 21.02L12 17.77L5.82 21.02L7 14.14L2 9.27L8.91 8.26L12 2Z" />
        </svg>
        <span class="text-sm font-medium text-[#12262a]">AI 智能菜谱推荐</span>
      </div>

      <!-- Title -->
      <h1 class="text-4xl sm:text-5xl md:text-6xl lg:text-7xl font-serif font-bold text-[#12262a] leading-tight mb-6 animate-slide-up">
        看看你的冰箱里
        <br />
        <span class="text-gradient">能做些什么</span>
      </h1>

      <!-- Description -->
      <p class="text-lg md:text-xl text-[#12262a]/70 max-w-2xl mx-auto mb-10 animate-slide-up-delay-200">
        输入你现有的食材，获取AI驱动的菜谱推荐。
        <br class="hidden sm:block" />
        让每一餐都充满惊喜，告别浪费。
      </p>

      <!-- CTA Buttons -->
      <div class="flex flex-col sm:flex-row gap-4 justify-center items-center animate-slide-up-delay-400">
        <Button
          size="lg"
          @click="scrollToIngredients"
          class="!rounded-full px-10 py-6 !text-lg shadow-xl shadow-[#2e5c41]/30 !bg-[#2e5c41] hover:!bg-[#234a33] !text-white"
        >
          添加食材
          <span class="ml-2 inline-block animate-bounce">
            <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 14l-7 7m0 0l-7-7m7 7V3" />
            </svg>
          </span>
        </Button>
        <Button
          size="lg"
          variant="outline"
          class="!rounded-full px-10 py-6 !text-lg border-2 border-[#2e5c41]/20 text-[#2e5c41] hover:bg-[#2e5c41]/5"
        >
          浏览热门菜谱
        </Button>
      </div>

      <!-- Stats -->
      <div class="mt-16 grid grid-cols-3 gap-8 max-w-lg mx-auto">
        <div
          v-for="(stat, index) in [
            { value: '1000+', label: '精选菜谱' },
            { value: '50+', label: '食材种类' },
            { value: '10万+', label: '快乐用户' },
          ]"
          :key="stat.label"
          :class="['text-center animate-scale-in', `animate-delay-${index * 100}`]"
        >
          <div class="text-2xl md:text-3xl font-serif font-bold text-[#2e5c41]">{{ stat.value }}</div>
          <div class="text-sm text-[#12262a]/60 mt-1">{{ stat.label }}</div>
        </div>
      </div>
    </div>

    <!-- Bottom Gradient Fade -->
    <div class="absolute bottom-0 left-0 right-0 h-32 bg-gradient-to-t from-white to-transparent" />
  </section>
</template>

<style scoped>
@keyframes float {
  0%, 100% {
    transform: translateY(0px) rotate(0deg);
  }
  25% {
    transform: translateY(-15px) rotate(-2deg);
  }
  50% {
    transform: translateY(-25px) rotate(0deg);
  }
  75% {
    transform: translateY(-15px) rotate(2deg);
  }
}

@keyframes pulse-slow {
  0%, 100% {
    transform: scale(1);
    opacity: 0.25;
  }
  50% {
    transform: scale(1.1);
    opacity: 0.4;
  }
}

@keyframes pulse {
  0%, 100% {
    transform: scale(1);
    opacity: 0.3;
  }
  50% {
    transform: scale(1.2);
    opacity: 0.5;
  }
}

@keyframes fade-in {
  from {
    opacity: 0;
  }
  to {
    opacity: 1;
  }
}

@keyframes slide-up {
  from {
    opacity: 0;
    transform: translateY(30px);
  }
  to {
    opacity: 1;
    transform: translateY(0);
  }
}

@keyframes scale-in {
  from {
    opacity: 0;
    transform: scale(0.95);
  }
  to {
    opacity: 1;
    transform: scale(1);
  }
}

@keyframes bounce {
  0%, 100% {
    transform: translateY(0);
  }
  50% {
    transform: translateY(4px);
  }
}

@keyframes shimmer {
  0% {
    background-position: -200% center;
  }
  100% {
    background-position: 200% center;
  }
}

.floating-ingredient {
  animation: float var(--float-duration, 6s) ease-in-out infinite;
}

.animate-fade-in {
  animation: fade-in 0.6s ease-out forwards;
}

.animate-slide-up {
  animation: slide-up 0.8s cubic-bezier(0.16, 1, 0.3, 1) forwards;
}

.animate-slide-up-delay-200 {
  animation: slide-up 0.8s cubic-bezier(0.16, 1, 0.3, 1) 0.2s forwards;
  opacity: 0;
}

.animate-slide-up-delay-400 {
  animation: slide-up 0.8s cubic-bezier(0.16, 1, 0.3, 1) 0.4s forwards;
  opacity: 0;
}

.animate-scale-in {
  animation: scale-in 0.6s cubic-bezier(0.16, 1, 0.3, 1) forwards;
}

.animate-bounce {
  animation: bounce 1.5s ease-in-out infinite;
}

.animate-delay-0 {
  animation-delay: 0s;
}

.animate-delay-100 {
  animation-delay: 0.1s;
}

.animate-delay-200 {
  animation-delay: 0.2s;
}

/* Gradient orbs with enhanced animation */
.gradient-orb {
  animation: pulse-slow 8s ease-in-out infinite;
}

.text-gradient {
  background: linear-gradient(135deg, #2e5c41 0%, #ff8a01 100%);
  -webkit-background-clip: text;
  -webkit-text-fill-color: transparent;
  background-clip: text;
}
</style>
